### ISSUE TITLE
Problem with pip install apache-airflow[gcp_api] - incompatible versions

### ISSUE THREAD

**Issue by jfine2358** [DataReplyUK/airflow-workshop-pydata-london-2018#2]
I've spent time setting up my laptop for this workshop. The instructions say

> You also need to install Airflow with support for gcp for the sake of this tutorial:
> 
> Install the latest with extras
> pip install apache-airflow[gcp_api]
> 
> Install the 1.9.0 with specific extras
> pip install apache-airflow[gcp_api]==1.9.0

But I've not found an error-free way of achieving this. My problem might be related to https://stackoverflow.com/questions/49047778/airflow-installation-failure-beamgcp

The errors I get are

> google-cloud-pubsub 0.26.0 has requirement google-cloud-core<0.26dev,>=0.25.0, but you'll have google-cloud-core 0.28.1 which is incompatible.
> grpcio 1.11.0 has requirement protobuf>=3.5.0.post1, but you'll have protobuf 3.3.0 which is incompatible.

If someone has a working installation, I'd be grateful if they could share its main features with me. I'll be able to provide more details after I've finished travelling today.

Or can I ignore these errors (he asked optimistically).

**Comment by kaxil** [comment]
Hi @jfine2358 Thanks for raising this issue. There seems to be some problem with Python3 & "gcp_api" integration as you rightly pointed out.

There are issues open already on Airflow JIRA:
* https://issues.apache.org/jira/browse/AIRFLOW-2343
* https://issues.apache.org/jira/browse/AIRFLOW-2266

I suggest you to create a Python2 Virtual Environment using:

```bash
virtualenv -p python2 airflow_workshop
```
OR

```bash
virtualenv -p python2.7 airflow_workshop
```

**Comment by jfine2358** [comment]
Hi Kaxil

Thank you for your prompt response. As I recall, I got a different problem
with Python 2. I hope try it again and let you know what happens later
tonight.

Jonathan

On 26 Apr 2018 16:54, "Kaxil Naik" <notifications@github.com> wrote:

Hi @jfine2358 <https://github.com/jfine2358> Thanks for raising this issue.
There seems to be some problem with Python3 & "gcp_api" integration as you
rightly pointed out.

There are issues open already on Airflow JIRA:

   - https://issues.apache.org/jira/browse/AIRFLOW-2343
   - https://issues.apache.org/jira/browse/AIRFLOW-2266

I suggest you to create a Python2 Virtual Environment using:

virtualenv -p python2 airflow_workshop

OR

virtualenv -p python2.7 airflow_workshop

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DataReplyUK/airflow-workshop-pydata-london-2018/issues/2#issuecomment-384693630>,
or mute the thread

**Comment by jfine2358** [comment]
I've tried Python2.7, and regret that it's still not working for me. I'll provide more information later tonight.

With 
> (airflow_workshop) (xenial)jfine2358@localhost:\~/airflow_workshop$ python
> Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
> [GCC 5.4.0 20160609] on linux2

and

> (airflow_workshop) (xenial)jfine2358@localhost:~/airflow_workshop$ python
> Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
> [GCC 5.4.0 20160609] on linux2

I get

> google-cloud-pubsub 0.26.0 has requirement google-cloud-core<0.26dev,>=0.25.0, but you'll have google-cloud-core 0.28.1 which is incompatible.
> apache-beam 2.4.0 has requirement dill==0.2.6, but you'll have dill 0.2.7.1 which is incompatible.
> apache-beam 2.4.0 has requirement httplib2<0.10,>=0.8, but you'll have httplib2 0.11.3 which is incompatible.
> googledatastore 7.0.1 has requirement httplib2<0.10,>=0.9.1, but you'll have httplib2 0.11.3 which is incompatible.

**Comment by kaxil** [comment]
Don't worry we will try and sort that out tomorrow during the tutorial.

**Comment by kaxil** [comment]
Hi @jfine2358 , just to let you know that after the meetup, I went home and worked on both the above mentioned JIRA issues and have resolved it and contributed to the project. So this will now work with Python 3.

The only thing is as this PR got merged it the master branch you will need to install airfow from Github.

```
pip install git+https://github.com/apache/incubator-airflow
pip install git+https://github.com/apache/incubator-airflow#egg=apache-airflow[gcp_api]
```
